{% set name = "kineticstoolkit_extensions" %}
{% set version = "0.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kineticstoolkit_extensions-{{ version }}.tar.gz
  sha256: 70a9a6589ddf611a0e38010e3e26f32ac62ddb24c52cf88fde1cdafad11c60de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - kineticstoolkit
    - ezc3d

test:
  imports:
    - kineticstoolkit_extensions
  requires:
    - python {{ python_min }}
  # No pip check because there is a problem with ezc3d packaged both in pypi and conda-forge, but not
  # recognized by pip when installed by conda-forge. In any case, the conda version of kineticstoolkit_extensions
  # only install conda packages, and the pip version of kineticstoolkit_extensions only installs pip packages.

about:
  home: https://kineticstoolkit.uqam.ca
  summary: Additional modules and development of new features for Kinetics Toolkit.
  license: Apache-2.0
  license_file: LICENSE.txt
  
extra:
  recipe-maintainers:
    - felixchenier
